# Generated by Django 3.2.12 on 2022-05-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_review_reviewcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
