# Generated by Django 3.2.12 on 2022-05-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20220525_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie_title',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
