# Generated by Django 3.2.12 on 2022-05-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20220519_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.BooleanField(),
        ),
    ]
